// Woordenlijst — formaat: [categorie, Duits, Nederlands, tip (optioneel)]
// Zelf woorden toevoegen? Voeg gewoon een regel toe in dezelfde stijl.
const CATEGORIES = {
  gevoel:  { name: "Gevoelens",          icon: "💛" },
  uitdr:   { name: "Uitdrukkingen",      icon: "💬" },
  beschr:  { name: "Omschrijvingen",     icon: "🎨" },
  vals:    { name: "Instinkers",         icon: "🪤" },
  werkw:   { name: "Werkwoorden",        icon: "🏃" },
  dagel:   { name: "Dagelijks leven",    icon: "🏠" },
  zinnen:  { name: "Handige zinnen",     icon: "🗣️" },
};

const WORDS = [
  // ---------- GEVOELENS ----------
  ["gevoel", "glücklich", "gelukkig"],
  ["gevoel", "traurig", "verdrietig"],
  ["gevoel", "müde", "moe"],
  ["gevoel", "wütend", "woedend"],
  ["gevoel", "sauer", "boos (spreektaal)", "Letterlijk 'zuur' — in spreektaal: boos."],
  ["gevoel", "froh", "blij"],
  ["gevoel", "nervös", "zenuwachtig"],
  ["gevoel", "aufgeregt", "opgewonden / gespannen"],
  ["gevoel", "ängstlich", "angstig"],
  ["gevoel", "enttäuscht", "teleurgesteld"],
  ["gevoel", "zufrieden", "tevreden"],
  ["gevoel", "stolz", "trots"],
  ["gevoel", "einsam", "eenzaam"],
  ["gevoel", "verliebt", "verliefd"],
  ["gevoel", "gelangweilt", "verveeld"],
  ["gevoel", "überrascht", "verrast"],
  ["gevoel", "neugierig", "nieuwsgierig"],
  ["gevoel", "eifersüchtig", "jaloers"],
  ["gevoel", "dankbar", "dankbaar"],
  ["gevoel", "entspannt", "ontspannen"],
  ["gevoel", "besorgt", "bezorgd"],
  ["gevoel", "verwirrt", "in de war"],
  ["gevoel", "erleichtert", "opgelucht"],
  ["gevoel", "beleidigt", "beledigd"],
  ["gevoel", "schüchtern", "verlegen / schuchter"],
  ["gevoel", "ungeduldig", "ongeduldig"],
  ["gevoel", "begeistert", "enthousiast"],
  ["gevoel", "hoffnungsvoll", "hoopvol"],
  ["gevoel", "die Freude", "de vreugde"],
  ["gevoel", "die Angst", "de angst"],
  ["gevoel", "die Wut", "de woede"],
  ["gevoel", "die Trauer", "het verdriet / de rouw"],
  ["gevoel", "die Sehnsucht", "het verlangen"],
  ["gevoel", "das Heimweh", "het heimwee"],
  ["gevoel", "die Liebe", "de liefde"],
  ["gevoel", "Ich vermisse dich.", "Ik mis je."],
  ["gevoel", "Mir ist langweilig.", "Ik verveel me."],
  ["gevoel", "Ich freue mich auf das Wochenende.", "Ik verheug me op het weekend."],
  ["gevoel", "Ich ärgere mich.", "Ik erger me."],
  ["gevoel", "Ich habe keine Lust.", "Ik heb geen zin."],
  ["gevoel", "Es tut mir leid.", "Het spijt me."],
  ["gevoel", "Mir geht's gut.", "Het gaat goed met me."],
  ["gevoel", "Mir geht's schlecht.", "Het gaat slecht met me."],
  ["gevoel", "Das ist mir peinlich.", "Dat vind ik gênant."],
  ["gevoel", "Ich bin sauer auf dich.", "Ik ben boos op je."],
  ["gevoel", "Ich habe Angst vor Hunden.", "Ik ben bang voor honden."],
  ["gevoel", "schadenfroh", "leedvermakelijk", "Die Schadenfreude: blij zijn met andermans pech."],

  // ---------- UITDRUKKINGEN ----------
  ["uitdr", "Ich drücke dir die Daumen.", "Ik duim voor je.", "Duitsers knijpen hun duimen in plaats van ze te 'draaien'."],
  ["uitdr", "Ich verstehe nur Bahnhof.", "Ik snap er helemaal niets van.", "Letterlijk: 'ik versta alleen station'."],
  ["uitdr", "Das ist nicht mein Bier.", "Dat is niet mijn probleem."],
  ["uitdr", "Das ist mir Wurst.", "Dat maakt me niks uit.", "Letterlijk: 'dat is mij worst'."],
  ["uitdr", "Schwein haben", "geluk hebben", "Letterlijk: 'een varken hebben'."],
  ["uitdr", "Ich habe die Nase voll.", "Ik heb er genoeg van."],
  ["uitdr", "Tomaten auf den Augen haben", "iets duidelijks over het hoofd zien"],
  ["uitdr", "auf dem Holzweg sein", "op het verkeerde spoor zitten"],
  ["uitdr", "Da steppt der Bär.", "Daar is het een groot feest."],
  ["uitdr", "Ich glaube, mein Schwein pfeift!", "Dat meen je niet!", "Uitroep van verbazing of ongeloof."],
  ["uitdr", "Hals- und Beinbruch!", "Succes! (breek een been)"],
  ["uitdr", "einen Kater haben", "een kater hebben"],
  ["uitdr", "Ich bin fix und fertig.", "Ik ben helemaal kapot."],
  ["uitdr", "Ich habe Schmetterlinge im Bauch.", "Ik heb vlinders in mijn buik."],
  ["uitdr", "unter vier Augen", "onder vier ogen"],
  ["uitdr", "Das Leben ist kein Ponyhof.", "Het leven is geen pretpark."],
  ["uitdr", "seinen Senf dazugeben", "ongevraagd je mening geven", "Letterlijk: 'zijn mosterd erbij doen'."],
  ["uitdr", "jemandem auf den Keks gehen", "iemand op de zenuwen werken", "Letterlijk: 'iemand op het koekje lopen'."],
  ["uitdr", "Ich bin ganz Ohr.", "Ik luister aandachtig."],
  ["uitdr", "Alles in Butter.", "Alles is in orde."],
  ["uitdr", "Kopf hoch!", "Kop op!"],
  ["uitdr", "Es regnet in Strömen.", "Het regent pijpenstelen."],
  ["uitdr", "Keine Ahnung.", "Geen idee."],
  ["uitdr", "Mal sehen.", "We zullen zien."],
  ["uitdr", "Na und?", "Nou en?"],
  ["uitdr", "Quatsch!", "Onzin!"],
  ["uitdr", "Na klar!", "Natuurlijk!"],
  ["uitdr", "Genau!", "Precies!"],
  ["uitdr", "Schade!", "Jammer!"],
  ["uitdr", "Ach so!", "O, zit dat zo!"],
  ["uitdr", "Doch!", "Jawel!", "Antwoord op een ontkennende vraag: 'Kommst du nicht?' — 'Doch!'"],
  ["uitdr", "Gute Besserung!", "Beterschap!"],
  ["uitdr", "Guten Appetit!", "Eet smakelijk!"],
  ["uitdr", "Prost!", "Proost!"],
  ["uitdr", "Mach's gut!", "Het ga je goed!"],
  ["uitdr", "Bis bald!", "Tot gauw!"],
  ["uitdr", "Herzlichen Glückwunsch!", "Van harte gefeliciteerd!"],
  ["uitdr", "Jetzt mal langsam!", "Rustig aan!"],
  ["uitdr", "Lass mich in Ruhe!", "Laat me met rust!"],
  ["uitdr", "Das kann doch nicht wahr sein!", "Dat kan toch niet waar zijn!"],
  ["uitdr", "Ich bin dran.", "Ik ben aan de beurt."],
  ["uitdr", "der Feierabend", "het einde van de werkdag"],
  ["uitdr", "Wie bitte?", "Wat zegt u?"],

  // ---------- OMSCHRIJVINGEN ----------
  ["beschr", "freundlich", "vriendelijk"],
  ["beschr", "nett", "aardig", "Let op: 'nett' is NIET 'net/netjes'."],
  ["beschr", "lustig", "grappig / vrolijk", "Let op: 'lustig' is NIET 'lusteloos'."],
  ["beschr", "ernst", "serieus"],
  ["beschr", "fleißig", "ijverig"],
  ["beschr", "faul", "lui"],
  ["beschr", "klug", "slim"],
  ["beschr", "dumm", "dom"],
  ["beschr", "hübsch", "knap / mooi"],
  ["beschr", "hässlich", "lelijk"],
  ["beschr", "dick", "dik"],
  ["beschr", "dünn", "dun"],
  ["beschr", "teuer", "duur"],
  ["beschr", "billig", "goedkoop"],
  ["beschr", "langweilig", "saai"],
  ["beschr", "spannend", "spannend"],
  ["beschr", "laut", "luid / lawaaierig"],
  ["beschr", "leise", "zacht / stil"],
  ["beschr", "schnell", "snel"],
  ["beschr", "langsam", "langzaam"],
  ["beschr", "schwer", "zwaar"],
  ["beschr", "leicht", "licht / makkelijk"],
  ["beschr", "schwierig", "moeilijk"],
  ["beschr", "einfach", "eenvoudig"],
  ["beschr", "sauber", "schoon"],
  ["beschr", "schmutzig", "vies / vuil"],
  ["beschr", "leer", "leeg"],
  ["beschr", "ruhig", "rustig"],
  ["beschr", "hilfsbereit", "behulpzaam"],
  ["beschr", "höflich", "beleefd"],
  ["beschr", "unhöflich", "onbeleefd"],
  ["beschr", "ehrlich", "eerlijk"],
  ["beschr", "großzügig", "vrijgevig"],
  ["beschr", "geizig", "gierig"],
  ["beschr", "pünktlich", "op tijd / stipt"],
  ["beschr", "lecker", "lekker (van eten)"],
  ["beschr", "gemütlich", "gezellig"],
  ["beschr", "sympathisch", "sympathiek"],
  ["beschr", "mutig", "moedig"],
  ["beschr", "vorsichtig", "voorzichtig"],
  ["beschr", "komisch", "raar / vreemd", "Instinker: 'komisch' betekent vaak 'raar', niet 'grappig'."],
  ["beschr", "blöd", "stom"],
  ["beschr", "hell", "licht (van kleur/ruimte)"],
  ["beschr", "dunkel", "donker"],
  ["beschr", "eng", "nauw / krap", "Instinker: 'eng' is 'nauw', niet 'griezelig'."],
  ["beschr", "breit", "breed"],
  ["beschr", "Er ist sehr nett.", "Hij is heel aardig."],
  ["beschr", "Sie hat lange, dunkle Haare.", "Zij heeft lang, donker haar."],
  ["beschr", "Die Wohnung ist hell und gemütlich.", "Het appartement is licht en gezellig."],

  // ---------- INSTINKERS (lijkt Nederlands, maar is het niet) ----------
  ["vals", "bellen", "blaffen", "Bellen (telefoon) is 'anrufen'."],
  ["vals", "doof", "dom / stom", "Doof (niet horen) is 'taub'."],
  ["vals", "taub", "doof"],
  ["vals", "schlimm", "erg / ernstig", "Slim is 'klug'."],
  ["vals", "das Meer", "de zee"],
  ["vals", "der See", "het meer"],
  ["vals", "die Tafel", "het schoolbord"],
  ["vals", "der Tisch", "de tafel"],
  ["vals", "das Kissen", "het kussen (om op te liggen)"],
  ["vals", "küssen", "kussen (zoenen)"],
  ["vals", "die Kerze", "de kaars"],
  ["vals", "die Kirsche", "de kers"],
  ["vals", "bekommen", "krijgen", "Niet 'bekomen'!"],
  ["vals", "also", "dus", "'Als' is 'wenn' of 'als'."],
  ["vals", "eventuell", "misschien / mogelijk", "Niet 'uiteindelijk' (= schließlich)."],
  ["vals", "bald", "binnenkort"],
  ["vals", "gleich", "zo meteen"],
  ["vals", "schon", "al"],
  ["vals", "der Zoll", "de douane"],
  ["vals", "das Rad", "de fiets / het wiel"],
  ["vals", "das Zimmer", "de kamer"],
  ["vals", "die Kneipe", "de kroeg"],
  ["vals", "der Grund", "de reden"],
  ["vals", "der Erfolg", "het succes"],
  ["vals", "der Unfall", "het ongeluk"],
  ["vals", "die Zeitung", "de krant"],
  ["vals", "das Gericht", "het gerecht / de rechtbank"],
  ["vals", "der Schmuck", "de sieraden"],
  ["vals", "die Schüssel", "de schaal / kom"],
  ["vals", "winken", "zwaaien"],
  ["vals", "die Rente", "het pensioen", "Rente (op geld) is 'die Zinsen'."],
  ["vals", "die Kammer", "de berging / het kamertje"],
  ["vals", "wer", "wie", "En 'wie' betekent 'hoe'!"],
  ["vals", "wie", "hoe"],

  // ---------- WERKWOORDEN ----------
  ["werkw", "sprechen", "spreken"],
  ["werkw", "arbeiten", "werken"],
  ["werkw", "wohnen", "wonen"],
  ["werkw", "kaufen", "kopen"],
  ["werkw", "bezahlen", "betalen"],
  ["werkw", "verstehen", "begrijpen / verstaan"],
  ["werkw", "vergessen", "vergeten"],
  ["werkw", "sich erinnern", "zich herinneren"],
  ["werkw", "lachen", "lachen"],
  ["werkw", "weinen", "huilen"],
  ["werkw", "schreien", "schreeuwen"],
  ["werkw", "flüstern", "fluisteren"],
  ["werkw", "umarmen", "omhelzen / knuffelen"],
  ["werkw", "streiten", "ruzie maken"],
  ["werkw", "sich beeilen", "zich haasten"],
  ["werkw", "warten", "wachten"],
  ["werkw", "suchen", "zoeken"],
  ["werkw", "finden", "vinden"],
  ["werkw", "brauchen", "nodig hebben"],
  ["werkw", "mögen", "lusten / leuk vinden"],
  ["werkw", "schmecken", "smaken"],
  ["werkw", "schlafen", "slapen"],
  ["werkw", "aufwachen", "wakker worden"],
  ["werkw", "aufstehen", "opstaan"],
  ["werkw", "kochen", "koken"],
  ["werkw", "putzen", "schoonmaken"],
  ["werkw", "spazieren gehen", "wandelen"],
  ["werkw", "vermissen", "missen"],
  ["werkw", "hoffen", "hopen"],
  ["werkw", "glauben", "geloven / denken"],
  ["werkw", "wissen", "weten"],
  ["werkw", "kennen", "kennen"],
  ["werkw", "fragen", "vragen"],
  ["werkw", "antworten", "antwoorden"],
  ["werkw", "helfen", "helpen"],
  ["werkw", "zeigen", "laten zien"],
  ["werkw", "fahren", "rijden"],
  ["werkw", "laufen", "lopen / rennen"],
  ["werkw", "erzählen", "vertellen"],
  ["werkw", "reden", "praten"],
  ["werkw", "sich freuen", "blij zijn"],
  ["werkw", "sich entschuldigen", "zich verontschuldigen"],

  // ---------- DAGELIJKS LEVEN ----------
  ["dagel", "der Termin", "de afspraak"],
  ["dagel", "die Verabredung", "het afspraakje / de date"],
  ["dagel", "das Wetter", "het weer"],
  ["dagel", "der Bahnhof", "het station"],
  ["dagel", "die Haltestelle", "de halte"],
  ["dagel", "der Flughafen", "het vliegveld"],
  ["dagel", "der Zug", "de trein"],
  ["dagel", "die Fahrkarte", "het (trein)kaartje"],
  ["dagel", "der Laden", "de winkel"],
  ["dagel", "die Wohnung", "het appartement / de woning"],
  ["dagel", "das Frühstück", "het ontbijt"],
  ["dagel", "das Mittagessen", "de lunch"],
  ["dagel", "das Abendessen", "het avondeten"],
  ["dagel", "das Brötchen", "het broodje"],
  ["dagel", "der Schlüssel", "de sleutel"],
  ["dagel", "die Tasche", "de tas"],
  ["dagel", "das Handy", "de mobiele telefoon"],
  ["dagel", "der Geburtstag", "de verjaardag"],
  ["dagel", "der Urlaub", "de vakantie"],
  ["dagel", "der Feiertag", "de feestdag"],
  ["dagel", "das Wochenende", "het weekend"],
  ["dagel", "der Kühlschrank", "de koelkast"],
  ["dagel", "die Küche", "de keuken"],
  ["dagel", "das Badezimmer", "de badkamer"],
  ["dagel", "der Arzt", "de dokter"],
  ["dagel", "die Apotheke", "de apotheek"],
  ["dagel", "die Straße", "de straat"],
  ["dagel", "die Ecke", "de hoek"],
  ["dagel", "die Brücke", "de brug"],
  ["dagel", "der Kellner", "de ober"],
  ["dagel", "die Speisekarte", "de menukaart"],
  ["dagel", "das Trinkgeld", "de fooi"],
  ["dagel", "die Rechnung", "de rekening"],
  ["dagel", "die Kasse", "de kassa"],
  ["dagel", "die Eltern", "de ouders"],
  ["dagel", "die Geschwister", "de broers en zussen"],
  ["dagel", "der Nachbar", "de buurman"],
  ["dagel", "die Einkaufsliste", "het boodschappenlijstje"],
  ["dagel", "der Regenschirm", "de paraplu"],

  // ---------- HANDIGE ZINNEN ----------
  ["zinnen", "Wie heißt du?", "Hoe heet je?"],
  ["zinnen", "Woher kommst du?", "Waar kom je vandaan?"],
  ["zinnen", "Ich komme aus den Niederlanden.", "Ik kom uit Nederland."],
  ["zinnen", "Was machst du beruflich?", "Wat doe je voor werk?"],
  ["zinnen", "Können Sie das bitte wiederholen?", "Kunt u dat alstublieft herhalen?"],
  ["zinnen", "Sprechen Sie bitte langsamer.", "Spreek alstublieft langzamer."],
  ["zinnen", "Was bedeutet das?", "Wat betekent dat?"],
  ["zinnen", "Wie sagt man das auf Deutsch?", "Hoe zeg je dat in het Duits?"],
  ["zinnen", "Ich verstehe das nicht.", "Ik begrijp dat niet."],
  ["zinnen", "Ich hätte gern einen Kaffee.", "Ik wil graag een koffie."],
  ["zinnen", "Die Rechnung, bitte.", "De rekening, alstublieft."],
  ["zinnen", "Wie viel kostet das?", "Hoeveel kost dat?"],
  ["zinnen", "Wo ist die Toilette?", "Waar is het toilet?"],
  ["zinnen", "Ich habe mich verlaufen.", "Ik ben verdwaald."],
  ["zinnen", "Wie spät ist es?", "Hoe laat is het?"],
  ["zinnen", "Hast du am Wochenende Zeit?", "Heb je dit weekend tijd?"],
  ["zinnen", "Ich bin gleich wieder da.", "Ik ben zo terug."],
  ["zinnen", "Das ist eine gute Idee.", "Dat is een goed idee."],
  ["zinnen", "Da bin ich deiner Meinung.", "Daar ben ik het met je eens."],
  ["zinnen", "Das sehe ich anders.", "Daar denk ik anders over."],
  ["zinnen", "Was ist los?", "Wat is er aan de hand?"],
  ["zinnen", "Mach dir keine Sorgen.", "Maak je geen zorgen."],
  ["zinnen", "Schön, dich kennenzulernen.", "Leuk je te leren kennen."],
  ["zinnen", "Kannst du mir helfen?", "Kun je me helpen?"],
  ["zinnen", "Es ist schon spät.", "Het is al laat."],
  ["zinnen", "Ich muss los.", "Ik moet gaan."],
  ["zinnen", "Wie war dein Tag?", "Hoe was je dag?"],
  ["zinnen", "Ich habe heute frei.", "Ik ben vandaag vrij."],
  ["zinnen", "Ich lerne seit kurzem Deutsch.", "Ik leer sinds kort Duits."],
  ["zinnen", "Das Essen schmeckt sehr gut.", "Het eten smaakt heel goed."],
  ["zinnen", "Ich bin müde, ich gehe ins Bett.", "Ik ben moe, ik ga naar bed."],
  ["zinnen", "Darf ich hier sitzen?", "Mag ik hier zitten?"],
];
